// Mock stock recommendation data — Indian (NSE), US, Crypto
// All prices and targets are illustrative for design purposes

window.RECOMMENDATIONS = [
  // ============ INDIAN (NSE) — BUY ============
  {
    id: "reliance",
    symbol: "RELIANCE",
    exchange: "NSE",
    name: "Reliance Industries",
    sector: "Energy / Conglomerate",
    market: "IN",
    currency: "₹",
    price: 2942.50,
    change: 1.84,
    action: "BUY",
    confidence: 87,
    risk: "LOW",
    horizon: "3–6 months",
    entry: { low: 2920, high: 2965 },
    targets: [3120, 3280, 3450],
    stopLoss: 2780,
    rr: 3.2,
    upside: 17.2,
    source: "Analyst + Algo",
    analyst: "Motilal Oswal",
    rationale: "Jio Platforms valuation re-rating expected post 5G monetization. Retail segment Q3 margins expanded 180bps. Refining benchmark cracks turning favourable into Q4.",
    catalysts: ["Jio IPO speculation H2 FY26", "Refining margin expansion", "Retail festive season"],
    tags: ["Largecap", "Index Heavy", "Conglomerate"],
    sparkline: [2810, 2825, 2850, 2842, 2880, 2905, 2898, 2925, 2940, 2942],
    posted: "2h ago",
    rsi: 58,
    pe: 27.4,
    marketCap: "19.9L Cr"
  },
  {
    id: "hdfcbank",
    symbol: "HDFCBANK",
    exchange: "NSE",
    name: "HDFC Bank",
    sector: "Banking",
    market: "IN",
    currency: "₹",
    price: 1684.20,
    change: 0.92,
    action: "BUY",
    confidence: 91,
    risk: "LOW",
    horizon: "6–12 months",
    entry: { low: 1670, high: 1700 },
    targets: [1780, 1880, 1950],
    stopLoss: 1590,
    rr: 2.8,
    upside: 15.8,
    source: "Analyst Consensus",
    analyst: "Jefferies",
    rationale: "Merger synergies playing out, NIM stabilizing at 3.6%. Deposit growth accelerating; CASA ratio improving sequentially. Re-rating story intact.",
    catalysts: ["NIM expansion FY26", "Branch productivity gains", "Credit cost normalization"],
    tags: ["Largecap", "Banking", "Defensive"],
    sparkline: [1620, 1635, 1640, 1655, 1648, 1665, 1672, 1680, 1685, 1684],
    posted: "4h ago",
    rsi: 62,
    pe: 18.9,
    marketCap: "12.8L Cr"
  },
  {
    id: "tatamotors",
    symbol: "TATAMOTORS",
    exchange: "NSE",
    name: "Tata Motors",
    sector: "Auto",
    market: "IN",
    currency: "₹",
    price: 982.40,
    change: 2.43,
    action: "BUY",
    confidence: 78,
    risk: "MEDIUM",
    horizon: "1–3 months",
    entry: { low: 968, high: 992 },
    targets: [1040, 1100, 1180],
    stopLoss: 920,
    rr: 2.4,
    upside: 20.1,
    source: "Algo Signal",
    analyst: "BULLSEYE Quant",
    rationale: "Breakout from 3-month consolidation on 2.1x avg volume. JLR Q3 wholesale beat. EV portfolio gaining traction. RSI cooling from overbought zone.",
    catalysts: ["JLR Q4 guidance", "EV deliveries", "Demerger progress"],
    tags: ["Largecap", "Auto", "Cyclical"],
    sparkline: [905, 920, 938, 945, 952, 968, 962, 975, 980, 982],
    posted: "1h ago",
    rsi: 67,
    pe: 14.2,
    marketCap: "3.6L Cr"
  },
  {
    id: "infy",
    symbol: "INFY",
    exchange: "NSE",
    name: "Infosys",
    sector: "IT Services",
    market: "IN",
    currency: "₹",
    price: 1842.60,
    change: -0.42,
    action: "HOLD",
    confidence: 64,
    risk: "LOW",
    horizon: "6–12 months",
    entry: { low: 1810, high: 1860 },
    targets: [1920, 2000, 2080],
    stopLoss: 1740,
    rr: 1.8,
    upside: 12.9,
    source: "Analyst",
    analyst: "Kotak Institutional",
    rationale: "Deal TCV strong but discretionary spend recovery slower than peers. Wait for Q4 guidance before adding aggressively. Margin levers intact.",
    catalysts: ["Q4 FY26 guidance", "BFSI discretionary uptick", "AI deal pipeline"],
    tags: ["Largecap", "IT", "Defensive"],
    sparkline: [1880, 1872, 1865, 1858, 1850, 1845, 1838, 1840, 1844, 1842],
    posted: "6h ago",
    rsi: 44,
    pe: 24.1,
    marketCap: "7.6L Cr"
  },
  {
    id: "adanigreen",
    symbol: "ADANIGREEN",
    exchange: "NSE",
    name: "Adani Green Energy",
    sector: "Renewables",
    market: "IN",
    currency: "₹",
    price: 1124.00,
    change: -2.84,
    action: "SELL",
    confidence: 72,
    risk: "HIGH",
    horizon: "1–2 months",
    entry: { low: 1115, high: 1140 },
    targets: [1040, 980, 920],
    stopLoss: 1185,
    rr: 2.1,
    upside: -18.1,
    direction: "SHORT",
    source: "Technical",
    analyst: "BULLSEYE Quant",
    rationale: "Head & shoulders breakdown on daily. Capacity addition guidance cut. Debt servicing concerns resurfacing. Below 50DMA with weak volume on bounces.",
    catalysts: ["Q3 capacity miss risk", "Debt refinance", "Promoter pledge"],
    tags: ["Smallcap", "Energy", "High Risk"],
    sparkline: [1240, 1220, 1198, 1175, 1180, 1158, 1142, 1130, 1135, 1124],
    posted: "3h ago",
    rsi: 32,
    pe: 88.0,
    marketCap: "1.8L Cr"
  },
  {
    id: "polycab",
    symbol: "POLYCAB",
    exchange: "NSE",
    name: "Polycab India",
    sector: "Capital Goods",
    market: "IN",
    currency: "₹",
    price: 6840,
    change: 3.21,
    action: "BUY",
    confidence: 82,
    risk: "MEDIUM",
    horizon: "6–9 months",
    entry: { low: 6750, high: 6900 },
    targets: [7300, 7800, 8200],
    stopLoss: 6450,
    rr: 2.6,
    upside: 19.9,
    source: "Analyst",
    analyst: "ICICI Securities",
    rationale: "Capex cycle tailwinds. FMEG segment turning profitable. T&D infra orders robust. Pricing power evident in wires & cables.",
    catalysts: ["Capex cycle", "FMEG margins", "Export growth"],
    tags: ["Midcap", "Capex Theme"],
    sparkline: [6520, 6580, 6610, 6650, 6720, 6780, 6810, 6790, 6830, 6840],
    posted: "5h ago",
    rsi: 64,
    pe: 48.2,
    marketCap: "1.0L Cr"
  },
  {
    id: "zomato",
    symbol: "ZOMATO",
    exchange: "NSE",
    name: "Zomato",
    sector: "Internet / Food Delivery",
    market: "IN",
    currency: "₹",
    price: 248.30,
    change: 4.12,
    action: "BUY",
    confidence: 76,
    risk: "MEDIUM",
    horizon: "3–6 months",
    entry: { low: 244, high: 252 },
    targets: [275, 305, 340],
    stopLoss: 224,
    rr: 2.9,
    upside: 22.8,
    source: "AI + Analyst",
    analyst: "BULLSEYE AI",
    rationale: "Blinkit GOV growing 100%+ YoY. Path to quick commerce profitability clearer. Food delivery contribution margin holding 7%+. Net cash positive.",
    catalysts: ["Blinkit breakeven", "Going-Out segment", "Q4 take rate"],
    tags: ["Largecap", "New Age", "Quick Commerce"],
    sparkline: [218, 225, 230, 234, 240, 238, 244, 245, 246, 248],
    posted: "2h ago",
    rsi: 71,
    pe: 142,
    marketCap: "2.2L Cr"
  },
  {
    id: "sbin",
    symbol: "SBIN",
    exchange: "NSE",
    name: "State Bank of India",
    sector: "Banking / PSU",
    market: "IN",
    currency: "₹",
    price: 812.50,
    change: 1.32,
    action: "BUY",
    confidence: 85,
    risk: "LOW",
    horizon: "6–12 months",
    entry: { low: 800, high: 820 },
    targets: [870, 920, 985],
    stopLoss: 760,
    rr: 3.1,
    upside: 21.2,
    source: "Analyst Consensus",
    analyst: "Macquarie",
    rationale: "Best-in-class PSU bank with sub-2% GNPA. Loan book growing 14%. Treasury gains and recovery write-backs cushion. Cheap on P/B vs private peers.",
    catalysts: ["Credit growth", "ROA expansion", "Subsidiary value unlock"],
    tags: ["Largecap", "PSU", "Banking"],
    sparkline: [780, 788, 795, 800, 805, 808, 810, 812, 814, 812],
    posted: "7h ago",
    rsi: 59,
    pe: 9.8,
    marketCap: "7.2L Cr"
  },
  {
    id: "irfc",
    symbol: "IRFC",
    exchange: "NSE",
    name: "Indian Railway Finance",
    sector: "PSU / Finance",
    market: "IN",
    currency: "₹",
    price: 148.20,
    change: 0.42,
    action: "HOLD",
    confidence: 56,
    risk: "MEDIUM",
    horizon: "12+ months",
    entry: { low: 142, high: 152 },
    targets: [165, 180, 195],
    stopLoss: 130,
    rr: 1.9,
    upside: 11.3,
    source: "Analyst",
    analyst: "Anand Rathi",
    rationale: "Re-rated post FY24 run. Dividend yield attractive but limited near-term catalysts. Railway capex visibility good but priced in.",
    catalysts: ["Budget capex allocation", "Railway PSU theme"],
    tags: ["PSU", "Dividend", "Railways"],
    sparkline: [145, 144, 146, 147, 148, 147, 148, 149, 148, 148],
    posted: "8h ago",
    rsi: 51,
    pe: 28.5,
    marketCap: "1.9L Cr"
  },
  {
    id: "trent",
    symbol: "TRENT",
    exchange: "NSE",
    name: "Trent",
    sector: "Retail",
    market: "IN",
    currency: "₹",
    price: 6420,
    change: 2.84,
    action: "BUY",
    confidence: 84,
    risk: "MEDIUM",
    horizon: "6–12 months",
    entry: { low: 6320, high: 6480 },
    targets: [6900, 7400, 8000],
    stopLoss: 5980,
    rr: 2.7,
    upside: 24.6,
    source: "Analyst",
    analyst: "Morgan Stanley",
    rationale: "Zudio store rollout best-in-class economics. SSSG holding 15%+. Westside revamp showing results. India retail compounder story.",
    catalysts: ["Zudio store adds", "Star format scaling"],
    tags: ["Largecap", "Retail", "Compounder"],
    sparkline: [6100, 6200, 6280, 6310, 6350, 6380, 6400, 6390, 6410, 6420],
    posted: "5h ago",
    rsi: 68,
    pe: 102,
    marketCap: "2.3L Cr"
  },
  {
    id: "dixon",
    symbol: "DIXON",
    exchange: "NSE",
    name: "Dixon Technologies",
    sector: "Electronics Mfg",
    market: "IN",
    currency: "₹",
    price: 14820,
    change: 5.42,
    action: "BUY",
    confidence: 81,
    risk: "HIGH",
    horizon: "6–9 months",
    entry: { low: 14600, high: 14900 },
    targets: [15800, 17000, 18500],
    stopLoss: 13800,
    rr: 2.4,
    upside: 24.8,
    source: "AI + Analyst",
    analyst: "BULLSEYE AI",
    rationale: "China+1 beneficiary in mobile, displays, IT hardware. PLI scheme tailwinds. Q3 revenue beat with strong order book visibility.",
    catalysts: ["PLI scheme expansion", "Mobile capacity ramp", "IT hardware PLI"],
    tags: ["Midcap", "EMS", "China+1"],
    sparkline: [13200, 13500, 13800, 14000, 14200, 14400, 14600, 14700, 14750, 14820],
    posted: "1h ago",
    rsi: 73,
    pe: 138,
    marketCap: "88K Cr"
  },
  {
    id: "tcs",
    symbol: "TCS",
    exchange: "NSE",
    name: "Tata Consultancy Services",
    sector: "IT Services",
    market: "IN",
    currency: "₹",
    price: 4082,
    change: -0.85,
    action: "HOLD",
    confidence: 68,
    risk: "LOW",
    horizon: "6–12 months",
    entry: { low: 4020, high: 4120 },
    targets: [4280, 4450, 4600],
    stopLoss: 3880,
    rr: 1.7,
    upside: 12.7,
    source: "Analyst Consensus",
    analyst: "Nomura",
    rationale: "Steady-state compounder. Margin profile best in class. Wait for clearer demand environment in BFSI before incremental adds.",
    catalysts: ["BFSI recovery", "AI deal wins", "Buyback"],
    tags: ["Largecap", "IT", "Defensive"],
    sparkline: [4150, 4140, 4125, 4110, 4095, 4080, 4075, 4080, 4085, 4082],
    posted: "9h ago",
    rsi: 42,
    pe: 28.4,
    marketCap: "14.8L Cr"
  },

  // ============ US STOCKS ============
  {
    id: "nvda",
    symbol: "NVDA",
    exchange: "NASDAQ",
    name: "NVIDIA",
    sector: "Semiconductors",
    market: "US",
    currency: "$",
    price: 142.84,
    change: 2.18,
    action: "BUY",
    confidence: 89,
    risk: "MEDIUM",
    horizon: "6–12 months",
    entry: { low: 140, high: 145 },
    targets: [158, 175, 195],
    stopLoss: 128,
    rr: 3.1,
    upside: 36.5,
    source: "AI + Analyst",
    analyst: "Wedbush",
    rationale: "Blackwell ramp ahead of schedule. Data center growth runway intact through CY27. Sovereign AI demand emerging. CUDA moat unchallenged.",
    catalysts: ["Blackwell GA Q1", "Sovereign AI orders", "Earnings May 28"],
    tags: ["Megacap", "AI", "Semiconductors"],
    sparkline: [130, 132, 135, 138, 140, 139, 141, 142, 143, 142],
    posted: "1h ago",
    rsi: 64,
    pe: 52.3,
    marketCap: "$3.5T"
  },
  {
    id: "aapl",
    symbol: "AAPL",
    exchange: "NASDAQ",
    name: "Apple",
    sector: "Consumer Tech",
    market: "US",
    currency: "$",
    price: 218.45,
    change: 0.84,
    action: "HOLD",
    confidence: 62,
    risk: "LOW",
    horizon: "6–12 months",
    entry: { low: 215, high: 222 },
    targets: [232, 245, 260],
    stopLoss: 202,
    rr: 1.7,
    upside: 19.0,
    source: "Analyst",
    analyst: "Morgan Stanley",
    rationale: "iPhone 17 super cycle thesis intact but services growth decelerating. Apple Intelligence rollout slower than expected. Valuation full.",
    catalysts: ["iPhone 17 launch Sep", "Services re-acceleration", "Buyback"],
    tags: ["Megacap", "Consumer Tech"],
    sparkline: [220, 221, 219, 217, 218, 220, 219, 218, 217, 218],
    posted: "4h ago",
    rsi: 51,
    pe: 33.2,
    marketCap: "$3.3T"
  },
  {
    id: "tsla",
    symbol: "TSLA",
    exchange: "NASDAQ",
    name: "Tesla",
    sector: "EV / Auto",
    market: "US",
    currency: "$",
    price: 348.20,
    change: 3.84,
    action: "BUY",
    confidence: 71,
    risk: "HIGH",
    horizon: "3–6 months",
    entry: { low: 340, high: 355 },
    targets: [385, 425, 475],
    stopLoss: 310,
    rr: 2.4,
    upside: 22.2,
    source: "AI Signal",
    analyst: "BULLSEYE AI",
    rationale: "Robotaxi narrative driving multiple expansion. Energy storage growing 90%+. FSD v13 progress. China deliveries stabilizing.",
    catalysts: ["Robotaxi rollout", "Q2 deliveries", "Energy backlog"],
    tags: ["Megacap", "EV", "AI"],
    sparkline: [310, 318, 325, 332, 338, 342, 345, 346, 348, 348],
    posted: "2h ago",
    rsi: 68,
    pe: 78.4,
    marketCap: "$1.1T"
  },
  {
    id: "amd",
    symbol: "AMD",
    exchange: "NASDAQ",
    name: "AMD",
    sector: "Semiconductors",
    market: "US",
    currency: "$",
    price: 168.40,
    change: -1.42,
    action: "BUY",
    confidence: 74,
    risk: "MEDIUM",
    horizon: "6–9 months",
    entry: { low: 162, high: 172 },
    targets: [188, 210, 235],
    stopLoss: 148,
    rr: 2.7,
    upside: 24.7,
    source: "Analyst",
    analyst: "Bank of America",
    rationale: "MI300X gaining traction at hyperscalers. CPU server share gains continuing. MI400 roadmap competitive vs Blackwell. Client recovery underway.",
    catalysts: ["MI400 launch", "Server share gains", "PC refresh"],
    tags: ["Largecap", "AI", "Semis"],
    sparkline: [180, 178, 175, 172, 170, 168, 165, 168, 170, 168],
    posted: "3h ago",
    rsi: 47,
    pe: 42.1,
    marketCap: "$272B"
  },
  {
    id: "googl",
    symbol: "GOOGL",
    exchange: "NASDAQ",
    name: "Alphabet",
    sector: "Internet",
    market: "US",
    currency: "$",
    price: 182.30,
    change: 1.24,
    action: "BUY",
    confidence: 83,
    risk: "LOW",
    horizon: "12+ months",
    entry: { low: 178, high: 184 },
    targets: [200, 220, 240],
    stopLoss: 168,
    rr: 2.6,
    upside: 21.7,
    source: "Analyst Consensus",
    analyst: "Goldman Sachs",
    rationale: "Gemini integration accelerating. Cloud growth re-accelerating to 30%+. YouTube monetization improving. AI search fears overblown.",
    catalysts: ["Gemini 3 rollout", "Cloud margins", "Waymo expansion"],
    tags: ["Megacap", "AI", "Cloud"],
    sparkline: [175, 177, 179, 178, 180, 181, 180, 182, 183, 182],
    posted: "5h ago",
    rsi: 58,
    pe: 26.4,
    marketCap: "$2.3T"
  },
  {
    id: "meta",
    symbol: "META",
    exchange: "NASDAQ",
    name: "Meta Platforms",
    sector: "Internet",
    market: "US",
    currency: "$",
    price: 612.80,
    change: 0.45,
    action: "HOLD",
    confidence: 66,
    risk: "MEDIUM",
    horizon: "6–12 months",
    entry: { low: 600, high: 620 },
    targets: [658, 700, 750],
    stopLoss: 560,
    rr: 1.9,
    upside: 14.6,
    source: "Analyst",
    analyst: "JPMorgan",
    rationale: "Ad revenue resilient but reality labs losses widening. Llama 4 capex commitment concerns near term. Awaiting clearer AI monetization.",
    catalysts: ["Reels monetization", "WhatsApp business", "AI ad tools"],
    tags: ["Megacap", "AI", "Social"],
    sparkline: [605, 608, 612, 615, 610, 608, 611, 613, 614, 612],
    posted: "6h ago",
    rsi: 52,
    pe: 28.1,
    marketCap: "$1.5T"
  },
  {
    id: "amzn",
    symbol: "AMZN",
    exchange: "NASDAQ",
    name: "Amazon",
    sector: "E-commerce / Cloud",
    market: "US",
    currency: "$",
    price: 224.60,
    change: 1.82,
    action: "BUY",
    confidence: 86,
    risk: "LOW",
    horizon: "12+ months",
    entry: { low: 220, high: 228 },
    targets: [245, 270, 295],
    stopLoss: 205,
    rr: 2.8,
    upside: 20.2,
    source: "Analyst Consensus",
    analyst: "Bernstein",
    rationale: "AWS reacceleration confirmed at 19%+ YoY. Retail margins structurally higher post-fulfillment regionalization. Ad business $60B+ run rate.",
    catalysts: ["AWS Gen-AI revenue", "Retail margin expansion", "Ads growth"],
    tags: ["Megacap", "Cloud", "Retail"],
    sparkline: [215, 218, 220, 222, 223, 224, 223, 224, 225, 224],
    posted: "4h ago",
    rsi: 61,
    pe: 38.4,
    marketCap: "$2.4T"
  },
  {
    id: "pltr",
    symbol: "PLTR",
    exchange: "NYSE",
    name: "Palantir",
    sector: "Software / AI",
    market: "US",
    currency: "$",
    price: 78.40,
    change: -2.14,
    action: "SELL",
    confidence: 69,
    risk: "HIGH",
    horizon: "1–3 months",
    entry: { low: 76, high: 80 },
    targets: [68, 60, 52],
    stopLoss: 86,
    rr: 2.2,
    upside: -23.4,
    direction: "SHORT",
    source: "Technical",
    analyst: "BULLSEYE Quant",
    rationale: "Valuation stretched at 280x forward earnings. Insider selling accelerating. RSI divergence on weekly. Trim positions, take profits.",
    catalysts: ["Earnings May 7", "Insider Form 4 filings", "Govt budget impact"],
    tags: ["Midcap", "AI", "Overvalued"],
    sparkline: [86, 84, 82, 81, 80, 79, 78, 79, 78, 78],
    posted: "2h ago",
    rsi: 38,
    pe: 280,
    marketCap: "$172B"
  },
  {
    id: "uber",
    symbol: "UBER",
    exchange: "NYSE",
    name: "Uber Technologies",
    sector: "Mobility",
    market: "US",
    currency: "$",
    price: 84.20,
    change: 2.41,
    action: "BUY",
    confidence: 79,
    risk: "MEDIUM",
    horizon: "6–9 months",
    entry: { low: 82, high: 86 },
    targets: [94, 105, 118],
    stopLoss: 76,
    rr: 2.5,
    upside: 24.7,
    source: "Analyst",
    analyst: "Wells Fargo",
    rationale: "Robotaxi partnerships (Waymo, Wayve) hedge AV disruption. Delivery EBITDA inflection. International mobility growing 30%+.",
    catalysts: ["Waymo expansion", "Q1 EBITDA beat", "Buyback execution"],
    tags: ["Largecap", "Mobility"],
    sparkline: [78, 80, 81, 82, 83, 82, 83, 84, 84, 84],
    posted: "5h ago",
    rsi: 63,
    pe: 32.4,
    marketCap: "$176B"
  },

  // ============ CRYPTO ============
  {
    id: "btc",
    symbol: "BTC",
    exchange: "Crypto",
    name: "Bitcoin",
    sector: "Layer 1",
    market: "CRYPTO",
    currency: "$",
    price: 98420,
    change: 1.84,
    action: "BUY",
    confidence: 81,
    risk: "MEDIUM",
    horizon: "6–12 months",
    entry: { low: 96000, high: 99000 },
    targets: [108000, 125000, 145000],
    stopLoss: 88000,
    rr: 2.4,
    upside: 27.0,
    source: "AI + On-chain",
    analyst: "BULLSEYE AI",
    rationale: "Spot ETF flows resumed positive. MVRV in healthy zone (not euphoric). Post-halving supply dynamics favourable through Q4. Sovereign adoption story building.",
    catalysts: ["ETF inflows", "Halving impact lag", "Strategic reserves talk"],
    tags: ["L1", "Store of Value"],
    sparkline: [92000, 93500, 94800, 95200, 96000, 96800, 97200, 97800, 98200, 98420],
    posted: "30m ago",
    rsi: 62,
    pe: null,
    marketCap: "$1.95T"
  },
  {
    id: "eth",
    symbol: "ETH",
    exchange: "Crypto",
    name: "Ethereum",
    sector: "Layer 1 / Smart Contract",
    market: "CRYPTO",
    currency: "$",
    price: 3420,
    change: 3.42,
    action: "BUY",
    confidence: 76,
    risk: "MEDIUM",
    horizon: "6–12 months",
    entry: { low: 3350, high: 3480 },
    targets: [3900, 4500, 5200],
    stopLoss: 3050,
    rr: 2.6,
    upside: 31.6,
    source: "On-chain + AI",
    analyst: "BULLSEYE AI",
    rationale: "L2 fee revenue rebounding. Pectra upgrade live. Spot ETF flows turning net positive after 6 weeks of outflows. ETH/BTC ratio bottoming.",
    catalysts: ["Pectra rollout effects", "ETF flows", "Re-staking growth"],
    tags: ["L1", "Smart Contracts"],
    sparkline: [3180, 3220, 3280, 3320, 3350, 3380, 3400, 3410, 3415, 3420],
    posted: "1h ago",
    rsi: 65,
    pe: null,
    marketCap: "$412B"
  },
  {
    id: "sol",
    symbol: "SOL",
    exchange: "Crypto",
    name: "Solana",
    sector: "Layer 1",
    market: "CRYPTO",
    currency: "$",
    price: 184.20,
    change: 5.84,
    action: "BUY",
    confidence: 78,
    risk: "HIGH",
    horizon: "3–6 months",
    entry: { low: 178, high: 188 },
    targets: [218, 260, 310],
    stopLoss: 158,
    rr: 2.8,
    upside: 41.1,
    source: "On-chain",
    analyst: "BULLSEYE Quant",
    rationale: "DEX volumes consistently above ETH. Memecoin activity sustained. Spot ETF filings progressing. Firedancer launch H2 2026.",
    catalysts: ["Solana ETF approval", "Firedancer mainnet", "Saga 2 launch"],
    tags: ["L1", "High Beta"],
    sparkline: [160, 165, 170, 172, 175, 178, 180, 182, 183, 184],
    posted: "45m ago",
    rsi: 69,
    pe: null,
    marketCap: "$84B"
  },
  {
    id: "doge",
    symbol: "DOGE",
    exchange: "Crypto",
    name: "Dogecoin",
    sector: "Memecoin",
    market: "CRYPTO",
    currency: "$",
    price: 0.412,
    change: -3.24,
    action: "HOLD",
    confidence: 48,
    risk: "VERY HIGH",
    horizon: "1–3 months",
    entry: { low: 0.39, high: 0.42 },
    targets: [0.48, 0.58, 0.72],
    stopLoss: 0.34,
    rr: 1.9,
    upside: 16.5,
    source: "Sentiment",
    analyst: "BULLSEYE AI",
    rationale: "Pure sentiment play. X/Tesla integration rumors recur. Position size small. Highly speculative — only with risk capital.",
    catalysts: ["X payments integration", "Memecoin season"],
    tags: ["Memecoin", "Speculative"],
    sparkline: [0.44, 0.43, 0.425, 0.42, 0.418, 0.415, 0.41, 0.413, 0.414, 0.412],
    posted: "1h ago",
    rsi: 42,
    pe: null,
    marketCap: "$60B"
  },
  {
    id: "bnb",
    symbol: "BNB",
    exchange: "Crypto",
    name: "BNB",
    sector: "Exchange Token",
    market: "CRYPTO",
    currency: "$",
    price: 712.40,
    change: 1.24,
    action: "HOLD",
    confidence: 58,
    risk: "MEDIUM",
    horizon: "3–6 months",
    entry: { low: 700, high: 720 },
    targets: [780, 850, 920],
    stopLoss: 650,
    rr: 1.8,
    upside: 14.2,
    source: "On-chain",
    analyst: "BULLSEYE Quant",
    rationale: "Quarterly burn supply mechanics constructive. BSC TVL recovering. Regulatory overhang easing. Range-bound trade favoured.",
    catalysts: ["Quarterly burn", "BSC ecosystem revival"],
    tags: ["L1", "Exchange"],
    sparkline: [695, 700, 705, 708, 710, 712, 711, 713, 714, 712],
    posted: "3h ago",
    rsi: 55,
    pe: null,
    marketCap: "$104B"
  },
  {
    id: "link",
    symbol: "LINK",
    exchange: "Crypto",
    name: "Chainlink",
    sector: "Oracle / DeFi",
    market: "CRYPTO",
    currency: "$",
    price: 24.80,
    change: 4.12,
    action: "BUY",
    confidence: 72,
    risk: "MEDIUM",
    horizon: "6–9 months",
    entry: { low: 24.20, high: 25.50 },
    targets: [29, 35, 42],
    stopLoss: 21.50,
    rr: 2.6,
    upside: 30.6,
    source: "AI + Analyst",
    analyst: "BULLSEYE AI",
    rationale: "CCIP adoption accelerating in TradFi (SWIFT, ANZ pilots). Staking yields attractive. Tokenized real-world assets thesis playing out.",
    catalysts: ["SWIFT mainnet", "RWA tokenization", "Staking v0.3"],
    tags: ["DeFi", "Oracle", "RWA"],
    sparkline: [22, 22.8, 23.4, 23.8, 24.2, 24.5, 24.6, 24.7, 24.75, 24.80],
    posted: "2h ago",
    rsi: 67,
    pe: null,
    marketCap: "$15.8B"
  }
];

window.NEWS_ITEMS = [
  { time: "12 min ago", source: "Reuters", title: "RBI holds rates at 6.5%, signals dovish pivot in H2 FY26", category: "Macro / IN", impact: "HIGH" },
  { time: "34 min ago", source: "Bloomberg", title: "Nvidia Blackwell shipments tracking ahead of internal targets — supply chain checks", category: "US / Tech", impact: "HIGH" },
  { time: "1h ago", source: "Mint", title: "Tata Motors JLR Q4 wholesale volumes beat consensus by 8%", category: "IN / Auto", impact: "MEDIUM" },
  { time: "1h ago", source: "CoinDesk", title: "Bitcoin spot ETFs see $342M net inflows on Friday, breaking 4-week drought", category: "Crypto", impact: "MEDIUM" },
  { time: "2h ago", source: "ET Now", title: "HDFC Bank Q4 NIM stabilizes at 3.61%, deposit growth at 18%", category: "IN / Banking", impact: "HIGH" },
  { time: "2h ago", source: "CNBC", title: "Tesla Robotaxi event pushed to June 12, analysts mixed", category: "US / EV", impact: "MEDIUM" },
  { time: "3h ago", source: "BusinessLine", title: "Zomato Blinkit crosses 1,000 dark stores — quick commerce share at 65%", category: "IN / Internet", impact: "MEDIUM" },
  { time: "3h ago", source: "The Block", title: "Solana ETF filings receive favourable preliminary feedback from SEC", category: "Crypto", impact: "HIGH" },
  { time: "4h ago", source: "Moneycontrol", title: "FII net buyers for 6th straight session, DII profit-booking continues", category: "IN / Flows", impact: "LOW" },
  { time: "5h ago", source: "Reuters", title: "Apple iPhone 17 production ramp delayed by 2 weeks at key supplier", category: "US / Tech", impact: "MEDIUM" }
];

window.ALERTS_DATA = [
  { id: 1, type: "TARGET_HIT", symbol: "RELIANCE", message: "Hit Target 1 at ₹3,120", time: "2h ago", triggered: true },
  { id: 2, type: "BREAKOUT", symbol: "TATAMOTORS", message: "Breakout above ₹980 confirmed on volume", time: "4h ago", triggered: true },
  { id: 3, type: "STOP_LOSS", symbol: "ADANIGREEN", message: "Approaching stop loss at ₹1,185 — short position", time: "1h ago", triggered: false },
  { id: 4, type: "NEW_PICK", symbol: "DIXON", message: "New BUY recommendation — Entry ₹14,600–14,900", time: "6h ago", triggered: true },
  { id: 5, type: "PRICE_ALERT", symbol: "BTC", message: "BTC crossed $98K — momentum confirmed", time: "30m ago", triggered: true },
  { id: 6, type: "NEWS", symbol: "NVDA", message: "Earnings May 28 — high confidence BUY active", time: "5h ago", triggered: false }
];

window.PORTFOLIO = [
  { symbol: "RELIANCE", market: "IN", qty: 50, avg: 2620, current: 2942.50, currency: "₹" },
  { symbol: "HDFCBANK", market: "IN", qty: 75, avg: 1540, current: 1684.20, currency: "₹" },
  { symbol: "ZOMATO", market: "IN", qty: 500, avg: 198, current: 248.30, currency: "₹" },
  { symbol: "NVDA", market: "US", qty: 12, avg: 118.40, current: 142.84, currency: "$" },
  { symbol: "BTC", market: "CRYPTO", qty: 0.18, avg: 78400, current: 98420, currency: "$" }
];
